name: Draw Lottery Winner

on:
  schedule:
    - cron: "0 23 * * *"  # Daily at 11 PM UTC
  workflow_dispatch:

jobs:
  draw-winner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Winner Draw Script
        run: python pick_winner.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "blockman-ai"
          git config --global user.email "bot@blockman.ai"
          git add winners_history.json

          if ! git diff --cached --quiet; then
            git commit -m "Auto-pick winner for daily lottery draw"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No new winners to commit."
          fi
